---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---
require("lua_extension")
require("cpp_class")
require("render_target")

--- @class RenderTexture 渲染到纹理
RenderTexture=class("RenderTexture",RenderTarget)

function RenderTexture:ctor()
    RenderTexture.super.ctor(self)
    ---@field color_texture_2d_ Texture2D
    self.color_texture_2d_=nil
end

--- 实例化C++ Class
function RenderTexture:InitCppClass()
    self.cpp_class_instance_=Cpp.RenderTexture()
end

function RenderTexture:color_texture_2d()
    if self.color_texture_2d_==nil then
        local cpp_color_texture_2d=self.cpp_class_instance_:color_texture_2d()
        self.color_texture_2d_=Texture2D.new_with(cpp_color_texture_2d)
    end
    return self.color_texture_2d_
end

function RenderTexture:depth_texture_2d()
    return self.cpp_class_instance_:depth_texture_2d()
end
