---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---
require("lua_extension")
require("cpp_class")
require("render_target")

--- @class RenderBuffer 渲染到纹理
RenderBuffer=class("RenderBuffer",RenderTarget)

function RenderBuffer:ctor()
    RenderBuffer.super.ctor(self)
end

--- 实例化C++ Class
function RenderBuffer:InitCppClass()
    self.cpp_class_instance_=Cpp.RenderBuffer()
end
