---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")
require("cpp_component")

MeshRenderer=class("MeshRenderer",CppComponent)

function MeshRenderer:ctor()
    MeshRenderer.super.ctor(self)
end

function MeshRenderer:InitCppComponent()
    ---@type Cpp.MeshRenderer
    self.cpp_component_instance_=Cpp.MeshRenderer()
end

--- 设置Material
--- @param material
function MeshRenderer:SetMaterial(material)
    self.cpp_component_instance_:SetMaterial(material)
end

--- 渲染
function MeshRenderer:Render()
    self.cpp_component_instance_:Render()
end