---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")

Animator=class("Animator",Component)

function Animator:ctor()
    Animator.super.ctor(self)
    ---@type Cpp.Animator
    self.animator_cpp_instance=Cpp.Animator() --创建对应的C++实例
end

function Animator:set_game_object(game_object)
    Animator.super:set_game_object(game_object)
    self.animator_cpp_instance:set_game_object(game_object.game_object_cpp_instance)--设置C++实例的game_object
end

function Animator:Awake()
    self.animator_cpp_instance:Awake()
end

function Animator:Update()
    self.animator_cpp_instance:Update()
end

function Animator:CppCallUpdate()

end