---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captainchen.
--- DateTime: 2022/5/17 21:46
---

require("lua_extension")
require("component")
require("game_object")

GameObjectManager={}


--- 存储所有的GameObject。
GameObjectManager.game_object_list_={}

--- 遍历GameObject
--- @param call_back function @回调函数
function GameObjectManager.Foreach(call_back)
    for _,value in pairs(GameObjectManager.game_object_list_) do
        call_back(value)
    end
end

