---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:54 PM
---

require("lua_extension")
require("component")

--- GameObject是游戏物体空节点，可以挂载多个组件
--- @class GameObject
GameObject=class("GameObject")

function GameObject:ctor(name)
    --- @type Component[] @组件列表
    self.components_map_={}
    --- @type Cpp.GameObject @C++ GameObject对象
    self.game_object_cpp_instance_=Cpp.GameObject(name)
    self.game_object_cpp_instance_:BindLuaObject(self)--将Lua对象绑定到C++对象上，以便在C++中调用Lua的方法，例如C++中调用Lua的Update方法。
end

--- 由C++调用，更新Lua组件，而Animator组件由C++ Animator调用Animator:CppCallUpdate()
function GameObject:CppCallUpdate()

end

--- 一种可行方式是由cpp调用lua入口update，然后lua驱动GameObject update，驱动组件update，cpp只提供组件实现。


---@param component_type table @组件类型
---@return Component @组件
function GameObject:AddComponent(component_type)
    local component_instance=component_type.new()
    self.components_map_[component_type]=component_instance
    component_instance:set_game_object(self)
    component_instance:Awake()
    return component_instance
end
