---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---
require("lua_extension")
require("cpp_class")

--- @class NoiseTexture 噪声纹理
NoiseTexture=class("NoiseTexture",CppClass)

function NoiseTexture:ctor()
    NoiseTexture.super.ctor(self)
    ---@field noise_texture_2d_ Texture2D
    self.noise_texture_2d_=nil
end

--- 实例化C++ Class
function NoiseTexture:InitCppClass()
    self.cpp_class_instance_=Cpp.NoiseTexture()
end

--- 初始化NoiseTexture
--- @param width number @宽
--- @param height number @高
--- @param noise number @噪声
function NoiseTexture:Init(width,height,noise)
    self.cpp_class_instance_:Init(width,height,sol2.convert_sequence_float(noise))
end

function NoiseTexture:width()
    return self.cpp_class_instance_:width()
end

function NoiseTexture:set_width(width)
    return self.cpp_class_instance_:set_width(width)
end

function NoiseTexture:height()
    return self.cpp_class_instance_:height()
end

function NoiseTexture:set_height(height)
    return self.cpp_class_instance_:set_height(height)
end

function NoiseTexture:frame_buffer_object_handle()
    return self.cpp_class_instance_:frame_buffer_object_handle()
end

function NoiseTexture:in_use()
    return self.cpp_class_instance_:in_use()
end

function NoiseTexture:set_in_use(in_use)
    return self.cpp_class_instance_:set_in_use(in_use)
end

function NoiseTexture:noise_texture_2d()
    if self.noise_texture_2d_==nil then
        local cpp_noise_texture_2d=self.cpp_class_instance_:noise_texture_2d()
        self.noise_texture_2d_=Texture2D.new_with(cpp_noise_texture_2d)
    end
    return self.noise_texture_2d_
end
