---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")
require("cpp_class")

PhysicMaterial=class("PhysicMaterial",CppClass)

function PhysicMaterial:ctor_with(cpp_class_instance,...)
    PhysicMaterial.super.ctor_with(self,cpp_class_instance,...)
end

function PhysicMaterial:static_friction()
    return self.cpp_class_instance_:static_friction()
end

function PhysicMaterial:set_static_friction(static_friction)
    return self.cpp_class_instance_:set_static_friction(static_friction)
end


function PhysicMaterial:dynamic_friction()
    return self.cpp_class_instance_:dynamic_friction()
end

function PhysicMaterial:set_dynamic_friction(dynamic_friction)
    return self.cpp_class_instance_:set_dynamic_friction(dynamic_friction)
end

function PhysicMaterial:restitution()
    return self.cpp_class_instance_:restitution()
end

function PhysicMaterial:set_restitution(restitution)
    return self.cpp_class_instance_:set_restitution(restitution)
end
