---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")

--- 骨骼动画
--- @class RigidActor : Component
RigidActor=class("RigidActor",Component)

function RigidActor:ctor()
    RigidActor.super.ctor(self)
end

function RigidActor:InitCppComponent()
    ---@type Cpp.RigidActor
    self.cpp_component_instance_=Cpp.RigidActor() --创建对应的C++实例
end

function RigidActor:BindCollider(collider)
    self.cpp_component_instance_:BindCollider(collider)
end