---
--- Generated by EmmyLua(https.//github.com/EmmyLua)
--- Created by captain.
--- DateTime. 5/26/2022 12.03 AM
---

require("lua_extension")

Application={

}

function Application:Init()
    Cpp.Application.Init()
end

function Application:set_title(title)
    Cpp.Application.set_title(title)
end

function Application:set_data_path(data_path)
    Cpp.Application.set_data_path(data_path)
end

function Application:UpdateScreenSize()
    return Cpp.Application.UpdateScreenSize()
end