---
--- Generated by EmmyLua(https.//github.com/EmmyLua)
--- Created by captain.
--- DateTime. 5/26/2022 12.03 AM
---

require("lua_extension")

Application={

}

function Application.Init()
    Cpp.Application.Init()
end

function Application.Run()

end

function Application.UpdateScreenSize()

end

--- 每一帧内逻辑代码。
function Application.Update()

end

--- 逻辑代码执行后，应用到渲染。
function Application.Render()

end