---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/21/2022 7:32 PM
---

require("lua_extension")

--- @class CppClass @表示当前Lua Class，是对C++ Class的封装
CppClass=class("CppClass")

function CppClass:ctor()
    self:InitCppClass()
end

--- 实例化C++ Class
function CppClass:InitCppClass()
    --- @public field cpp_class_instance_ table @C++ Class实例
    self.cpp_class_instance_=nil
end

function CppClass:cpp_class_instance()
    return self.cpp_class_instance_
end