---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/26/2022 12:03 AM
---

require("lua_extension")

Debug={

}

function Debug.Init()
    Cpp.Debug.Init()
end