---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")

--- 骨骼动画
--- @class Collider : Component
Collider=class("Collider",Component)

function Collider:ctor()
    Collider.super.ctor(self)
end

function Collider:InitCppComponent()
    ---@type Cpp.Collider
    self.cpp_component_instance_=Cpp.Collider() --创建对应的C++实例
end

function Collider:px_shape()
    return self.cpp_component_instance_:px_shape()
end

function Collider:CreatePhysicMaterial()
    return self.cpp_component_instance_:CreatePhysicMaterial()
end

function Collider:CreateShape()
    return self.cpp_component_instance_:CreateShape()
end

function Collider:RegisterToRigidActor()
    return self.cpp_component_instance_:RegisterToRigidActor()
end