---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")

--- @class SphereCollider : Component
SphereCollider=class("SphereCollider",Collider)

function SphereCollider:ctor()
    SphereCollider.super.ctor(self)
end

function SphereCollider:InitCppComponent()
    ---@type Cpp.SphereCollider
    self.cpp_component_instance_=Cpp.SphereCollider() --创建对应的C++实例
end