---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")

--- @class RigidStatic : RigidActor
RigidStatic=class("RigidStatic",RigidActor)

function RigidStatic:ctor()
    RigidStatic.super.ctor(self)
end

function RigidStatic:InitCppComponent()
    ---@type Cpp.RigidStatic
    self.cpp_component_instance_=Cpp.RigidStatic() --创建对应的C++实例
end