---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---
require("lua_extension")
require("cpp_class")

--- @class RenderTextureGeometryBuffer 渲染到GBuffer
RenderTextureGeometryBuffer=class("RenderTextureGeometryBuffer",RenderTexture)

function RenderTextureGeometryBuffer:ctor()
    RenderTextureGeometryBuffer.super.ctor(self)
end

--- 实例化C++ Class
function RenderTextureGeometryBuffer:InitCppClass()
    self.cpp_class_instance_=Cpp.RenderTextureGeometryBuffer()
end

--- 初始化RenderTextureGeometryBuffer，在GPU生成帧缓冲区对象(FrameBufferObject)
--- @param width number @宽
--- @param height number @高
function RenderTextureGeometryBuffer:Init(width,height)
    self.cpp_class_instance_:Init(width,height)
end
