---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---
require("lua_extension")
require("cpp_class")

--- @class RenderTextureGeometryBuffer 渲染到GBuffer
RenderTextureGeometryBuffer=class("RenderTextureGeometryBuffer",RenderTexture)

function RenderTextureGeometryBuffer:ctor()
    RenderTextureGeometryBuffer.super.ctor(self)
end

--- 实例化C++ Class
function RenderTextureGeometryBuffer:InitCppClass()
    self.cpp_class_instance_=Cpp.RenderTextureGeometryBuffer()
end
