---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")
require("cpp_class")

--- @class RenderTexture 渲染到纹理
RenderTexture=class("RenderTexture",CppClass)

function RenderTexture:ctor()
    RenderTexture.super.ctor(self)
end

--- 实例化C++ Class
function RenderTexture:InitCppClass()
    self.cpp_class_instance_=Cpp.RenderTexture()
end

--- 初始化RenderTexture，在GPU生成帧缓冲区对象(FrameBufferObject)
--- @param width number @宽
--- @param height number @高
function RenderTexture:Init(width,height)
    self.cpp_class_instance_:Init(width,height)
end

function RenderTexture:width()
    return self.cpp_class_instance_:width()
end

function RenderTexture:set_width(width)
    return self.cpp_class_instance_:set_width(width)
end

function RenderTexture:height()
    return self.cpp_class_instance_:height()
end

function RenderTexture:set_height(height)
    return self.cpp_class_instance_:set_height(height)
end

function RenderTexture:frame_buffer_object_handle()
    return self.cpp_class_instance_:frame_buffer_object_handle()
end

function RenderTexture:in_use()
    return self.cpp_class_instance_:in_use()
end

function RenderTexture:set_in_use(in_use)
    return self.cpp_class_instance_:set_in_use(in_use)
end
