---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captainchen.
--- DateTime: 2022/5/17 21:46
---

require("lua_extension")
require("component")
require("game_object")

GameObjectManager={}

--- 存储所有的GameObject。
GameObjectManager.game_object_list_={}

--- 添加GameObject
--- @param game_object GameObject
function GameObjectManager:Add(game_object)
    table.insert(self.game_object_list_,game_object)
end


function GameObjectManager:Update()
    for _,game_object in pairs(self.game_object_list_) do
        game_object:Update()
    end
end

