---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")

--- @class Component @组件
Component=class("Component")

function Component:ctor()
    self.game_object_=nil
end

--- 设置目标GameObject
--- @return void
function Component:set_game_object(game_object)
    self.game_object_=game_object
end

--- 返回组件所属的GameObject
--- @return GameObject @返回组件所属的GameObject
function Component:game_object()
    return self.game_object_
end

function Component:OnEnable()

end

function Component:Awake()
    
end

function Component:Update()

end

--- 渲染之前
function Component:OnPreRender()

end

--- 渲染之后
function Component:OnPostRender()

end

function Component:OnDisable()

end