---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")
require("cpp_component")

UIImage=class("UIImage",CppComponent)

function UIImage:ctor()
    UIImage.super.ctor(self)
end

function UIImage:InitCppComponent()
    ---@type Cpp.UIImage
    self.cpp_component_instance_=Cpp.UIImage() --创建对应的C++实例
end

function UIImage:set_image_normal(image)
    self.cpp_component_instance_:set_image_normal()
end