---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/29/2022 11:08 PM
---

require("lua_extension")

Transform=class("Transform",Component)

function Transform:ctor()
    Transform.super.ctor(self)
end

function Transform:InitCppComponent()
    ---@type Cpp.Transform
    self.cpp_component_instance_=Cpp.Transform()
end


function Transform:position()
    return self.cpp_component_instance_:position()
end

function Transform:rotation()
    return self.cpp_component_instance_:rotation()
end

function Transform:scale()
    return self.cpp_component_instance_:scale()
end

function Transform:local_position()
    return self.cpp_component_instance_:local_position()
end

function Transform:local_rotation()
    return self.cpp_component_instance_:local_rotation()
end

function Transform:local_scale()
    return self.cpp_component_instance_:local_scale()
end

function Transform:set_local_position(local_position)
    return self.cpp_component_instance_:set_local_position(local_position)
end

function Transform:set_local_rotation(local_position)
    return self.cpp_component_instance_:set_local_rotation(local_position)
end

function Transform:set_local_scale(local_position)
    return self.cpp_component_instance_:set_local_scale(local_position)
end