---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")
require("cpp_component")

UICamera=class("UICamera",CppComponent)

function UICamera:ctor()
    UICamera.super.ctor(self)
    ---@type Cpp.UICamera
    self.cpp_component_instance_=Cpp.UICamera() --创建对应的C++实例
end