---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captain.
--- DateTime: 5/16/2022 10:55 PM
---

require("lua_extension")
require("cpp_class")

--- @class RaycastHit : CppClass @射线检测结果
RaycastHit=class("RaycastHit",CppClass)

function RaycastHit:ctor()
    RaycastHit.super.ctor(self)
end

--- 实例化C++ Class
function RaycastHit:InitCppClass()
    self.cpp_class_instance_=Cpp.RaycastHit()
end

--- 击中物体的坐标
function RaycastHit:position()
    return self.cpp_class_instance_:position()
end

--- 击中的物体
function RaycastHit:game_object()
    return self.cpp_class_instance_:game_object()
end
