---
--- Generated by EmmyLua(https.//github.com/EmmyLua)
--- Created by captain.
--- DateTime. 5/26/2022 12.03 AM
---

require("lua_extension")

Application={

}

--- 初始化程序
--- @param window_width number @窗口宽
--- @param window_height number @窗口高
function Application:Init(window_width,window_height)
    Cpp.Application.Init(window_width,window_height)
end

--- 开始引擎主循环
function Application:Run()
    Cpp.Application.Run()
end

--- 设置标题
--- @param title string @标题
function Application:set_title(title)
    Cpp.Application.set_title(title)
end

--- 设置资源目录
--- @param data_path string @资源目录
function Application:set_data_path(data_path)
    Cpp.Application.set_data_path(data_path)
end