---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by captainchen.
--- DateTime: 2024/3/19 17:32
---

ObjectReferenceManager = {
    ---@type table<table, number>
    reference_count_ = {}
}

--- 将对象引用次数+1
--- @param obj table
function ObjectReferenceManager:Retain(obj)
    if obj == nil then
        return
    end
    if self.reference_count_[obj] == nil then
        self.reference_count_[obj] = 1
    else
        self.reference_count_[obj] = self.reference_count_[obj] + 1
    end
end

--- 将对象引用次数-1
--- @param obj table
function ObjectReferenceManager:Release(obj)
    if obj == nil then
        return
    end
    if self.reference_count_[obj] == nil then
        return
    end
    self.reference_count_[obj] = self.reference_count_[obj] - 1
    if self.reference_count_[obj] <= 0 then
        self.reference_count_[obj] = nil
    end
end
